# Generated by Django 6.0.5 on 2026-06-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['created_at']},
        ),
    ]
